services:
  postgres-crm:
    image: postgres
    container_name: global-retail-postgres-crm
    environment:
      POSTGRES_USER: ${POSTGRES_OLTP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_OLTP_PASSWORD}
      POSTGRES_DB: ${POSTGRES_OLTP_DB}
    ports:
      - "${POSTGRES_OLTP_PORT}:5432"
    volumes:
      - oltp_data:/var/lib/postgresql/data

  postgres-dw:
    image: postgres
    container_name: global-retail-postgres-dw
    environment:
      POSTGRES_USER: ${POSTGRES_OLAP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_OLAP_PASSWORD}
      POSTGRES_DB: ${POSTGRES_OLAP_DB}
    ports:
      - "${POSTGRES_OLAP_PORT}:5432"
    volumes:
      - olap_data:/var/lib/postgresql/data

volumes:
  oltp_data:
  olap_data:
